FROM ubuntu:18.04
MAINTAINER Alberto Soragna alberto dot soragna at gmail dot com

# working directory
ENV HOME /root
WORKDIR $HOME

# create an empty .bashrc file
RUN touch $HOME/.bashrc
RUN > $HOME/.bashrc

# general utilities
RUN apt-get update && apt-get install -y \
  apt-utils \
  curl \
  nano \
  locales \
  lsb-release \
  gnupg2

# install gcc6 compiler and toolchain
RUN apt-get install -y \
  gcc-6 \
  g++-6 \
  g++-6-arm-linux-gnueabihf

# set gcc6 as default compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6  

#### ROS2

RUN locale-gen en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

RUN curl http://repo.ros2.org/repos.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

# ROS setup requirements
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  python3-colcon-common-extensions \
  python-rosdep \
  python3-vcstool \
  python3-pip

# pip
RUN pip3 install --upgrade pip

RUN python3 -m pip install -U \
  argcomplete \
  flake8 \
  flake8-blind-except \
  flake8-builtins \
  flake8-class-newline \
  flake8-comprehensions \
  flake8-deprecated \
  flake8-docstrings \
  flake8-import-order \
  flake8-quotes \
  pytest-repeat \
  pytest-rerunfailures

# install Fast-RTPS dependencies
RUN apt-get install --no-install-recommends -y \
  libasio-dev \
  libtinyxml2-dev \
  libopensplice67

# dependencies for RViz
RUN apt-get install -y \
  libfreetype6-dev \
  libfreeimage-dev \
  libzzip-dev \
  libxrandr-dev \
  libxaw7-dev \
  freeglut3-dev \
  libgl1-mesa-dev \
  libcurl4-openssl-dev \
  libqt5core5a \
  libqt5gui5 \
  libqt5opengl5 \
  libqt5widgets5 \
  libxaw7-dev \
  libgles2-mesa-dev \
  libglu1-mesa-dev \
  qtbase5-dev


RUN apt-get update && apt-get install -y \
  git \
  libeigen3-dev



