FROM ubuntu:18.04
MAINTAINER Alberto Soragna alberto dot soragna at gmail dot com

# working directory
ENV HOME /root
WORKDIR $HOME

# create an empty .bashrc file
RUN touch $HOME/.bashrc
RUN > $HOME/.bashrc

# general utilities
RUN apt-get update && apt-get install -y \
  apt-utils \
  curl \
  nano \
  locales \
  lsb-release \
  gnupg2

# install gcc6 compiler and toolchain
RUN apt-get install -y \
  gcc-6 \
  g++-6 \
  g++-6-arm-linux-gnueabihf

# set gcc6 as default compiler
RUN update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6  

#### ROS2

RUN locale-gen en_US.UTF-8
RUN update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8
ENV LANG en_US.UTF-8

RUN curl http://repo.ros2.org/repos.key | apt-key add -
RUN sh -c 'echo "deb [arch=amd64,arm64] http://repo.ros2.org/ubuntu/main `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'

ENV TZ=America/Los_Angeles
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata

# ROS setup requirements
RUN apt-get update && apt-get install -y \
  build-essential \
  cmake \
  python3-colcon-common-extensions \
  python-rosdep


RUN apt-get install -y \
  software-properties-common \
  git

# use python 3.5
RUN add-apt-repository ppa:deadsnakes/ppa -y
RUN apt-get update && apt-get install -y python3.5

RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.5 /usr/bin/python3


